spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: dev_user
    password: andy
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true

#   This is for the use of generate sql query that hibernate produce - guru_database_create.sql
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql
